### ISSUE TITLE
Issue with this release

### ISSUE THREAD

**Issue by mewtek** [the5dcrew/encoder#1]
Hi! Would appreciate if you went out of your way to ask permission before cloning this repository. I also don't appreciate the re-licensing of my code and open-sourcing of it without explicit permission. I've taken the actions necessary to get this taken down. Thanks!

**Comment by brenden7158** [comment]
Hi April, You had the encoder open-source before, but you privated them on October 18 so @TWCBranden could not get access to the encoder, The code was fully open-source up till that point, Not to mention you never put a license on your code. I will still credit you as you made it. If you wanna further discuss this, you can reach out to me.
